"""add clientes table

Revision ID: 4fe39cdd1c78
Revises: c951ddda1fe4
Create Date: 2026-07-25 17:09:31.038348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe39cdd1c78'
down_revision: Union[str, Sequence[str], None] = 'c951ddda1fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_whatsapp'), 'clientes', ['whatsapp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_whatsapp'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
