"""initial_schema

Revision ID: 7f9610191db8
Revises: 
Create Date: 2026-07-21 08:11:25.964640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9610191db8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_comercio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medios_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medios_pago_codigo'), 'medios_pago', ['codigo'], unique=True)
    op.create_table('metodos_entrega',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 0', name='orden_no_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_entrega_codigo'), 'metodos_entrega', ['codigo'], unique=True)
    op.create_table('comercios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=150), nullable=False),
    sa.Column('nombre_corto', sa.String(length=80), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=False),
    sa.Column('whatsapp', sa.String(length=30), nullable=False),
    sa.Column('calle', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('piso_departamento', sa.String(length=50), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('zona_horaria', sa.String(length=100), server_default='America/Argentina/Buenos_Aires', nullable=False),
    sa.Column('moneda', sa.String(length=3), server_default='ARS', nullable=False),
    sa.Column('idioma', sa.String(length=10), server_default='es-AR', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estado_comercio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comercios_cuit'), 'comercios', ['cuit'], unique=False)
    op.create_index(op.f('ix_comercios_slug'), 'comercios', ['slug'], unique=True)
    op.create_index(op.f('ix_comercios_whatsapp'), 'comercios', ['whatsapp'], unique=True)
    op.create_table('categorias_productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comercio', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_comercio'], ['comercios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_productos_id_comercio'), 'categorias_productos', ['id_comercio'], unique=False)
    op.create_table('comercio_medios_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comercio', sa.Integer(), nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('titular', sa.String(length=150), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_comercio'], ['comercios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medios_pago.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_comercio', 'id_medio_pago', name='comercio_medio_pago_unico')
    )
    op.create_index(op.f('ix_comercio_medios_pago_id_comercio'), 'comercio_medios_pago', ['id_comercio'], unique=False)
    op.create_index(op.f('ix_comercio_medios_pago_id_medio_pago'), 'comercio_medios_pago', ['id_medio_pago'], unique=False)
    op.create_table('comercio_metodos_entrega',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comercio', sa.Integer(), nullable=False),
    sa.Column('id_metodo_entrega', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 0', name='orden_no_negativo'),
    sa.ForeignKeyConstraint(['id_comercio'], ['comercios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_metodo_entrega'], ['metodos_entrega.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_comercio', 'id_metodo_entrega', name='comercio_metodo_unico')
    )
    op.create_index(op.f('ix_comercio_metodos_entrega_id_comercio'), 'comercio_metodos_entrega', ['id_comercio'], unique=False)
    op.create_index(op.f('ix_comercio_metodos_entrega_id_metodo_entrega'), 'comercio_metodos_entrega', ['id_metodo_entrega'], unique=False)
    op.create_table('presentaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comercio', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 0', name='orden_no_negativo'),
    sa.ForeignKeyConstraint(['id_comercio'], ['comercios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_comercio', 'codigo', name='comercio_presentacion_codigo_unico'),
    sa.UniqueConstraint('id_comercio', 'descripcion', name='comercio_presentacion_descripcion_unica')
    )
    op.create_index(op.f('ix_presentaciones_id_comercio'), 'presentaciones', ['id_comercio'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 0', name='orden_no_negativo'),
    sa.ForeignKeyConstraint(['id_categoria_producto'], ['categorias_productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_categoria_producto', 'nombre', name='categoria_producto_nombre_unico')
    )
    op.create_index(op.f('ix_productos_id_categoria_producto'), 'productos', ['id_categoria_producto'], unique=False)
    op.create_table('producto_presentaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_presentacion', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 0', name='orden_no_negativo'),
    sa.ForeignKeyConstraint(['id_presentacion'], ['presentaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_producto', 'id_presentacion', name='producto_presentacion_unico')
    )
    op.create_index(op.f('ix_producto_presentaciones_id_presentacion'), 'producto_presentaciones', ['id_presentacion'], unique=False)
    op.create_index(op.f('ix_producto_presentaciones_id_producto'), 'producto_presentaciones', ['id_producto'], unique=False)
    op.create_table('producto_precios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto_presentacion', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('precio >= 0', name='precio_no_negativo'),
    sa.ForeignKeyConstraint(['id_producto_presentacion'], ['producto_presentaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('id_producto_presentacion', 'producto_precios', ['id_producto_presentacion'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_producto_presentacion', table_name='producto_precios')
    op.drop_table('producto_precios')
    op.drop_index(op.f('ix_producto_presentaciones_id_producto'), table_name='producto_presentaciones')
    op.drop_index(op.f('ix_producto_presentaciones_id_presentacion'), table_name='producto_presentaciones')
    op.drop_table('producto_presentaciones')
    op.drop_index(op.f('ix_productos_id_categoria_producto'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_presentaciones_id_comercio'), table_name='presentaciones')
    op.drop_table('presentaciones')
    op.drop_index(op.f('ix_comercio_metodos_entrega_id_metodo_entrega'), table_name='comercio_metodos_entrega')
    op.drop_index(op.f('ix_comercio_metodos_entrega_id_comercio'), table_name='comercio_metodos_entrega')
    op.drop_table('comercio_metodos_entrega')
    op.drop_index(op.f('ix_comercio_medios_pago_id_medio_pago'), table_name='comercio_medios_pago')
    op.drop_index(op.f('ix_comercio_medios_pago_id_comercio'), table_name='comercio_medios_pago')
    op.drop_table('comercio_medios_pago')
    op.drop_index(op.f('ix_categorias_productos_id_comercio'), table_name='categorias_productos')
    op.drop_table('categorias_productos')
    op.drop_index(op.f('ix_comercios_whatsapp'), table_name='comercios')
    op.drop_index(op.f('ix_comercios_slug'), table_name='comercios')
    op.drop_index(op.f('ix_comercios_cuit'), table_name='comercios')
    op.drop_table('comercios')
    op.drop_index(op.f('ix_metodos_entrega_codigo'), table_name='metodos_entrega')
    op.drop_table('metodos_entrega')
    op.drop_index(op.f('ix_medios_pago_codigo'), table_name='medios_pago')
    op.drop_table('medios_pago')
    op.drop_table('estado_comercio')
    # ### end Alembic commands ###
