"""add pedidos table

Revision ID: c951ddda1fe4
Revises: 7f9610191db8
Create Date: 2026-07-25 16:17:56.432371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c951ddda1fe4'
down_revision: Union[str, Sequence[str], None] = '7f9610191db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_medio_pago', sa.Integer(), nullable=True),
    sa.Column('id_metodo_entrega', sa.Integer(), nullable=True),
    sa.Column('datetime_entrega_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado_pedido', sa.Enum('borrador', 'ingresado', 'preparacion', 'terminado', 'entregado', 'cancelado', name='estado_pedido'), server_default='borrador', nullable=False),
    sa.Column('fecha_alta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_modificacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_medio_pago'], ['medios_pago.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_metodo_entrega'], ['metodos_entrega.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    # ### end Alembic commands ###
