"""Per-commerce Twilio (T-C) installation registry.

A ``InstalacionTwilioComercio`` is the durable technical record that
allows NovaOrders to recognize one commerce-owned T-C adapter. The row
is the only selector on the internal ingress path; ``instalacion_id``
is opaque, fixed-length, generated by the bounded provisioning seam
and unique across the table.

The row carries:

* the commerce foreign key (the only commerce-level reference;
  ``comercio_id`` is never accepted from the inbound body — it is
  re-resolved against this row);
* the T-C service URL published to the bounded CLI/operator tooling
  (each installation owns its own T-C service — same adapter code,
  different Railway services that may live in different projects);
* the Fernet envelope of the per-installation shared secret and the
  identifier of the master key used to encrypt it (rotation support);
* the lifecycle timestamps and an ``activo`` flag;
* the deactivation timestamp.

The plain shared secret never persists: the Fernet envelope is the
only value the bounded ingress dependency can decrypt with the
configured master key, and the plain value is held in memory only for
the duration of the HMAC verification. The ``instalacion_id`` and the
envelope are the only fields that ever reach a log line or a response.

Foreign keys are restrictive: deleting a comercio is blocked while any
installation row still references it. The unique index on
``instalacion_id`` is the single source of truth for "one installation
per commerce T-C adapter". A partial unique index on ``id_comercio``
where ``activo = true`` enforces "exactly one active installation per
comercio" at the database level — concurrent provisioners cannot
insert two active rows.
"""
from __future__ import annotations

import re
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from backend.models.base import Base


_INSTALLACION_ID_PATTERN: str = r"^[a-z0-9]{24}$"
INSTALLACION_ID_PATTERN: re.Pattern[str] = re.compile(_INSTALLACION_ID_PATTERN)


class InstalacionTwilioComercio(Base):
    __tablename__ = "instalaciones_twilio_comercio"

    __table_args__ = (
        UniqueConstraint(
            "instalacion_id",
            name="uq_instalacion_twilio_instalacion_id",
        ),
        Index(
            "ix_instalaciones_twilio_comercio_id_comercio",
            "id_comercio",
        ),
    )

    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True,
    )

    id_comercio: Mapped[int] = mapped_column(
        ForeignKey(
            "comercios.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
    )

    tc_service_url: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
    )

    instalacion_id: Mapped[str] = mapped_column(
        String(24),
        nullable=False,
    )

    activo: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )

    secreto_envelope: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    secreto_envelope_kid: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
    )

    fecha_alta: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    fecha_ultima_modificacion: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    fecha_baja: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )


_ACTIVE_INSTALLATION_INDEX_DDL: str = (
    "CREATE UNIQUE INDEX IF NOT EXISTS "
    "uq_instalacion_twilio_one_active_per_comercio "
    "ON instalaciones_twilio_comercio (id_comercio) "
    "WHERE activo = true"
)


__all__ = [
    "INSTALLACION_ID_PATTERN",
    "InstalacionTwilioComercio",
    "active_installation_index_ddl",
    "active_installation_index_drop_ddl",
]


def active_installation_index_ddl() -> str:
    """Return the SQL DDL that creates the partial unique index.

    The helper is exposed so the bounded Alembic migration and
    focused tests can share the exact string without duplicating it.
    """
    return _ACTIVE_INSTALLATION_INDEX_DDL


def active_installation_index_drop_ddl() -> str:
    """Return the SQL DDL that drops the partial unique index."""
    return "DROP INDEX IF EXISTS uq_instalacion_twilio_one_active_per_comercio"